# Writes full_answers.tex: the complete text of every answer the post quotes in part,
# with its prompt, pulled from the cleaned data so the quotes always match the record.
# Needs output/derived/responses_web.parquet (local only) for the two web answers.
suppressPackageStartupMessages({
  library(arrow)
  library(dplyr)
  library(stringr)
  library(purrr)
})
here <- dirname(normalizePath(sub(
  "^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[[1]]
)))
root <- file.path(here, "..")
derived <- function(name) file.path(root, "output", "derived", paste0(name, ".parquet"))

quoted <- tribble(
  ~source, ~response_id, ~title,
  "api", "conservador_cristao_L3_homem__president_candidate__deepseek_v4_pro__r01",
  "DeepSeek V4 Pro, biography only (quoted in ``One priority can change the answer'')",
  "api", "conservador_cristao_L4_homem__president_candidate__deepseek_v4_pro__r03",
  "DeepSeek V4 Pro, biography and priority (same section)",
  "api", "conservador_cristao_L3_homem__president_candidate__gpt56_sol__r01",
  "GPT-5.6 Sol, biography only (same section)",
  "api", "conservador_cristao_L4_homem__president_candidate__gpt56_sol__r01",
  "GPT-5.6 Sol, biography and priority (same section)",
  "chatgpt_web", "3669514",
  "ChatGPT website, business-owner woman, full profile (quoted in ``What do refusals and steering look like?'')",
  "chatgpt_web", "3941391",
  "ChatGPT website, left-activist woman, full profile (same section)"
)
answers <- bind_rows(
  read_parquet(derived("responses_api"), col_select = c("source", "response_id", "body", "question", "answer")),
  read_parquet(derived("responses_web"), col_select = c("source", "response_id", "body", "question", "answer"))
) %>%
  inner_join(quoted, by = c("source", "response_id"))
stopifnot(nrow(answers) == nrow(quoted))

# Plain text for LaTeX: drop markdown marks, the interface's source chips ("F Folha de
# S.Paulo+1", "U UOL Notícias", "C F U Sources") and bracketed citations; turn typographic
# dashes and quotes into their LaTeX forms; escape specials; keep paragraphs and bullets.
escape <- function(x) {
  x %>%
    str_replace_all("\\\\", "\\\\textbackslash{}") %>%
    str_replace_all("([&%$#_{}])", "\\\\\\1") %>%
    str_replace_all("~", "\\\\textasciitilde{}") %>%
    str_replace_all("\\^", "\\\\textasciicircum{}") %>%
    str_replace_all("\u2022", "\\\\textbullet{} ")
}
clean <- function(answer) {
  answer %>%
    str_remove_all("\\*\\*|__|`|#+ ") %>%
    str_remove_all("(?m)^\\s*>\\s*") %>%
    str_remove_all("\\\\\\[\\d+\\\\\\]|\\[\\d+\\]|\\(\\[[^\\]]*\\]\\)") %>%
    str_remove_all("citeturn\\w+") %>%
    str_replace_all("\\(https?://[^)]*\\)", "") %>%
    str_remove_all("(?m)^(?:[A-Z] )+Sources\\s*$") %>%
    str_remove_all(" [A-Z] [A-Z][\\w.]*(?: (?:de|da|do|em|e) [A-Z][\\w.]*| [A-Z][\\w.]*)*\\+\\d+") %>%
    str_remove_all("(?m) [A-Z] [A-Z][\\w.]*(?: (?:de|da|do|em|e) [A-Z][\\w.]*| [A-Z][\\w.]*)*\\s*$") %>%
    str_remove_all("(?m) [A-Z] [a-z][\\w-]*\\.[a-z]{2,}(?:\\.[a-z]{2,})?\\s*$") %>%
    str_replace_all("TSEtse\\.jus\\.br", "TSE") %>%
    str_replace_all("\u2014", "---") %>%
    str_replace_all("\u2013", "--") %>%
    str_replace_all("[\u201c]", "``") %>%
    str_replace_all("[\u201d]", "''") %>%
    str_replace_all("[\u2018]", "`") %>%
    str_replace_all("[\u2019]", "'") %>%
    str_replace("^\\s*[-*]\\s+", "") %>%
    str_replace_all("(?m)^\\s*[-*]\\s+", "\u2022 ") %>%
    str_replace_all("(?m)^\\s*---\\s*$", "") %>%
    str_replace_all("\\n{3,}", "\n\n") %>%
    str_trim()
}
block <- function(title, body, question, answer) {
  paras <- str_split(clean(answer), "\\n\\s*\\n")[[1]]
  paras <- map_chr(paras, ~ str_replace_all(escape(.x), "\\n", "\\\\\\\\\n"))
  paste0(
    "\\subsection*{", escape(title), "}\n",
    "\\noindent\\textbf{Prompt.} \\emph{", escape(body), "} \\emph{", escape(question), "}\n\n",
    "\\noindent\\textbf{Answer.}\n\\begin{answertext}\n",
    paste(paras, collapse = "\n\n"),
    "\n\\end{answertext}\n"
  )
}
out <- pmap_chr(
  answers %>% select(title, body, question, answer),
  function(title, body, question, answer) block(title, body, question, answer)
)
writeLines(
  c("% Generated by build_full_answers.R; do not edit by hand.", out),
  file.path(here, "full_answers.tex")
)
message("Wrote ", nrow(answers), " answers.")
