# Writes refusal_table.tex from output/tables/refusal_by_steering.csv.
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(stringr)
})
here <- dirname(normalizePath(sub(
  "^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[[1]]
)))
root <- file.path(here, "..")
source_lines <- readLines(file.path(root, "00_setup.R"))
eval(parse(text = source_lines[grep("^model_levels <- ", source_lines):(grep("^level_order <- ", source_lines) - 1)]))
pct <- function(x) if_else(x == 0, "0", paste0(round(100 * x)))
tab <- read_csv(file.path(root, "output", "tables", "refusal_by_steering.csv"), show_col_types = FALSE) %>%
  mutate(model = unname(model_labels[model_key]), order = match(model_key, model_levels)) %>%
  arrange(desc(names_one)) %>%
  transmute(
    model, answers = format(answers, big.mark = ","),
    a = pct(refuses_no_steer), b = pct(refuses_and_steers), c = pct(steers_no_refusal),
    d = pct(neither), e = pct(names_one),
    f = if_else(is.na(steer_given_refusal), "--", pct(steer_given_refusal)),
    g = if_else(is.na(refusal_given_steer), "--", pct(refusal_given_steer))
  )
rows <- paste0(
  tab$model, " & ", tab$answers, " & ", tab$a, " & ", tab$b, " & ", tab$c, " & ", tab$d,
  " & ", tab$e, " & ", tab$f, " & ", tab$g, " \\\\"
)
writeLines(c(
  "% Generated by build_refusal_table.R; do not edit by hand.",
  "\\begin{table}[h]\\centering\\small",
  "\\caption{Refusal language against steering, by configuration. Shares of labelled answers, full profiles, specific-candidate wording, both offices.}",
  "\\label{tab:refusal}",
  "\\begin{tabular}{lrrrrrrrr}",
  "\\toprule",
  " & & \\multicolumn{4}{c}{Share of answers (\\%)} & & \\multicolumn{2}{c}{Conditional (\\%)} \\\\",
  "\\cmidrule(lr){3-6}\\cmidrule(lr){8-9}",
  "Configuration & Answers & \\shortstack[r]{Refuses,\\\\no steer} & \\shortstack[r]{Refuses\\\\and steers} & \\shortstack[r]{Steers,\\\\no refusal} & Neither & \\shortstack[r]{Names\\\\one} & \\shortstack[r]{Steers $\\mid$\\\\refuses} & \\shortstack[r]{Refuses $\\mid$\\\\steers} \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
), file.path(here, "refusal_table.tex"))
message("Wrote refusal_table.tex with ", nrow(tab), " rows.")
